name: Generate Go from Protobuf

on:
  push:
    tags:
      - "v*"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install protoc & plugins
        run: |
          sudo apt-get update -y
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate Go code
        run: |
          # Очистить прошлую генерацию
          rm -rf golang
          # Создать каталоги модулей
          for pkg in order payment shipping; do
            mkdir -p "golang/${pkg}"
            protoc \
              --go_out=golang/${pkg} --go_opt=paths=source_relative \
              --go-grpc_out=golang/${pkg} --go-grpc_opt=paths=source_relative \
              ${pkg}/${pkg}.proto
            # инициализировать go.mod, если его ещё нет
            if [ ! -f golang/${pkg}/go.mod ]; then
              (cd golang/${pkg} && \
                go mod init github.com/muerewa/grpc-protos/golang/${pkg})
            fi
            (cd golang/${pkg} && go mod tidy)
          done

      - name: Commit & push generated code
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add golang
          git commit -m "chore: regenerate Go code for $GITHUB_REF_NAME"
          git push
